name: application
description: "A new project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8

  # Network.
  dio: 5.7.0
  json_annotation: 4.9.0

  # Dependecies.
  get_it: 8.0.2

  # State Management.
  provider: 6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 4.0.0

  # Network.
  build_runner: 2.4.13
  json_serializable: 6.9.0

flutter:
  uses-material-design: true
